Github actions test#7

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -30,14 +30,14 @@ jobs:
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         script: cd ${{ secrets.REMOTE_PATH }}
                 echo "WHOAMI $(whoami)"
-                echo "Current dir $(pwd)"
-                ls -l
-                echo "Checking Maven..."
-                which mvn || echo "Maven not found"
-                mvn -v || echo "Maven version not found"
-                  
-                echo "Building project..."
-                mvn clean package -DskipTests || { echo 'Build failed'; exit 1; }
-                  
-                echo "Build complete. Listing target/:"
-                ls -l target
+#                echo "Current dir $(pwd)"
+#                ls -l
+#                echo "Checking Maven..."
+#                which mvn || echo "Maven not found"
+#                mvn -v || echo "Maven version not found"
+#
+#                echo "Building project..."
+#                mvn clean package -DskipTests || { echo 'Build failed'; exit 1; }
+#
+#                echo "Build complete. Listing target/:"
+#                ls -l target
